//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ErpDBEntities : DbContext
    {
        public ErpDBEntities()
            : base("name=ErpDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TblCustomer> TblCustomers { get; set; }
        public virtual DbSet<TblEmployee> TblEmployees { get; set; }
        public virtual DbSet<TblInventory> TblInventories { get; set; }
        public virtual DbSet<TblLegalForm> TblLegalForms { get; set; }
        public virtual DbSet<TblPartner> TblPartners { get; set; }
        public virtual DbSet<TblProductCategory> TblProductCategories { get; set; }
        public virtual DbSet<TblProduct> TblProducts { get; set; }
        public virtual DbSet<TblPurchas> TblPurchases { get; set; }
        public virtual DbSet<TblSale> TblSales { get; set; }
        public virtual DbSet<TblSupplier> TblSuppliers { get; set; }
        public virtual DbSet<TblTransaction> TblTransactions { get; set; }
        public virtual DbSet<TblUnit> TblUnits { get; set; }
        public virtual DbSet<TblUser> TblUsers { get; set; }
    }
}
