//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPurchas
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public int SupplierId { get; set; }
        public int TransactionId { get; set; }
        public decimal Amount { get; set; }
        public decimal Price { get; set; }
        public decimal UnitPrice { get; set; }
    
        public virtual TblProduct TblProduct { get; set; }
        public virtual TblSupplier TblSupplier { get; set; }
        public virtual TblTransaction TblTransaction { get; set; }
    }
}
